AWSTemplateFormatVersion: 2010-09-09
Description: >
  Image Builder pipeline used to build Fluent Bit pre-installed AMI.
Parameters:
  Prefix:
    Default: 'poc'
    Type: String
    Description: >
      Resource name in this template should be prefixed with this word.
  DeploymentBucket:
    Default: 'deployment-bucket'
    Type: String
    Description: >
      S3 bucket used to deploy this template.
  ComponentDocUri:
    Default: 's3://deployment-bucket/component.yaml'
    Type: String
    Description: >
      Image Builder AWSTOE component document.
  ComponentVersion:
    Default: '1.0.0'
    Type: String
    Description: >
      Image Builder AWSTOE component version.
  ImageRecipeParentAmiId:
    Default: 'ami-12345'
    Type: String
    Description: >
      Base AMI of this building target.
  ImageRecipeVersion:
    Default: 1.0.0
    Type: String
    Description: >
      Image Builder ImageRecipe version.
  BasicStack:
    Default: 'stack-vpc'
    Type: String
    Description: >
      Stack name of VPC used to deploy the following infrastructure.
  FluentBitInstanceType:
    Default: 't3.small'
    Type: String
    Description: >
      EC2 instance type used to run fluentbit.
  FluentBitHttpPort:
    Default: 3891
    Type: Number
    Description: >
      Fluent Bit HTTP input plugin's listen port.
  FluentBitHealthCheckPort:
    Default: 2020
    Type: Number
    Description: >
      Fluent Bit HTTP server port.
Resources:
  IBEC2InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref Prefix, 'EC2InstanceProfileForImageBuilder']]
      Description: >
        'Role used to run AWSTOE of Image Builder.'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder'
        - 'arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds'
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  IBEC2InstanceProfile: 
      Type: AWS::IAM::InstanceProfile
      Properties: 
        Path: "/"
        Roles: 
          - !Ref IBEC2InstanceProfileRole
  FluentBitComponent:
    Type: AWS::ImageBuilder::Component
    Properties: 
      Name: !Join ['-', [!Ref Prefix, 'fluentbit']]
      Description: 'Install fluent-bit.'
      ChangeDescription: 'Initial version.'
      Platform: 'Linux'
      Uri: !Ref ComponentDocUri
      Version: !Ref ComponentVersion
  FluentBitImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Join ['-', [!Ref Prefix, 'fluentbit']]
      Description: >
        'Used to orchestrate buiding components for target AMI.'
      Version: !Ref ImageRecipeVersion
      ParentImage: !Ref ImageRecipeParentAmiId
      Components:
        - ComponentArn: !Ref FluentBitComponent
#      BlockDeviceMappings:
#        - DeviceName: "/dev/xvda"
#          Ebs:
#            DeleteOnTermination: true
#            Encrypted: false
#            VolumeType: "gp2"
#            VolumeSize: 100
  InfraConfig:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Join ['-', [!Ref Prefix, 'common']]
      InstanceProfileName: !Ref IBEC2InstanceProfile
      Description: >
        'Common infrastructure configure used to build AMI.'
      InstanceTypes:
        - 'm5.large'
      Logging:
        S3Logs:
          S3BucketName: !Ref DeploymentBucket
          S3KeyPrefix: 'image-builder/logs'
      TerminateInstanceOnFailure: true
  FluentBitDistConfig:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Join ['-', [!Ref Prefix, 'fluentbit']]
      Description: >
        'Configure AMI distribution options.'
      Distributions:
        - Region: !Ref AWS::Region
          AmiDistributionConfiguration:
            Name: !Join ['-', [!Ref Prefix, 'fluentbit - {{ imagebuilder:buildDate }}']] 
            Description: >
              'AMI with Fluent Bit(and corresponding config) pre-installed.'
  FluentBitImage:
      Type: AWS::ImageBuilder::Image
      Properties:
        ImageRecipeArn: !Ref FluentBitImageRecipe
        InfrastructureConfigurationArn: !Ref InfraConfig
        DistributionConfigurationArn: !Ref FluentBitDistConfig
        EnhancedImageMetadataEnabled: True
#-----------------------------------------------
  FluentBitEC2InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref Prefix, 'FluentBitEC2InstanceProfileRole']]
      Description: >
        'Role used to run Fluent Bit and forward data to Kinesis Stream.'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonKinesisFullAccess'
  FluentBitEC2InstanceProfile: 
      Type: "AWS::IAM::InstanceProfile"
      Properties: 
        Path: "/"
        Roles: 
          - !Ref FluentBitEC2InstanceProfileRole
  FluentBitInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ['-', [!Ref Prefix, 'fluentbit-sg']]
      GroupDescription: 'Enable HTTP access on fluentbit input listen port.'
      VpcId:
        Fn::ImportValue: !Sub '${BasicStack}-Vpc'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref FluentBitHttpPort
          ToPort: !Ref FluentBitHttpPort
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref FluentBitHealthCheckPort
          ToPort: !Ref FluentBitHealthCheckPort
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: 'Name'
          Value: !Join ['-', [!Ref Prefix, 'fluentbit-sg']]
  FluentBitLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn:
      - FluentBitImage
      - FluentBitInstanceSG
    Properties:
      LaunchTemplateName: !Join ['-', [!Ref Prefix, 'fluentbit']]
      LaunchTemplateData:
        IamInstanceProfile: 
          Name: !Ref FluentBitEC2InstanceProfile
        ImageId: !GetAtt FluentBitImage.ImageId
        InstanceType: !Ref FluentBitInstanceType
        SecurityGroupIds: 
          - !GetAtt FluentBitInstanceSG.GroupId
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              DeleteOnTermination: true
              Encrypted: false
              VolumeType: "gp2"
              VolumeSize: 100
  FluentBitTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join ['-', [!Ref Prefix, 'fluentbit-tg']]
      VpcId: 
        Fn::ImportValue: !Sub '${BasicStack}-Vpc'
      HealthCheckEnabled: true
      HealthCheckPath: '/api/v1/health'
      HealthCheckPort: !Ref FluentBitHealthCheckPort
      HealthCheckProtocol: 'HTTP'
      TargetType: 'instance'
      Protocol: 'TCP'
      Port: !Ref FluentBitHttpPort
Outputs:
  LaunchTemplateValue:
    Description: >
      Fluent Bit LaunchTemplate ID.
    Value: !Ref FluentBitLaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-FluentBitLT'
  LaunchTemplateLatestVersionNumberValue:
    Description: >
      Fluent Bit LaunchTemplate latest version number.
    Value: !GetAtt FluentBitLaunchTemplate.LatestVersionNumber
    Export:
      Name: !Sub '${AWS::StackName}-FluentBitLTLatestVersion'
  TargetGroupValue:
    Description: >
      Fluent Bit NLB TargetGroup.
    Value: !Ref FluentBitTargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-FluentBitTargetGroup'