AWSTemplateFormatVersion: 2010-09-09
Description: >
  Analyze videos from different sites and tag these videos.
Parameters:
  Prefix:
    Default: 'poc'
    Type: String
    Description: >
      Resource name in this template should be prefixed with this word
  BasicStack:
    Default: stack-vpc
    Type: String
    Description: >
      Stack name of VPC used to deploy the following infrastructure.
  ImagePipelineStack:
    Default: stack-image-builder
    Type: String
    Description: >
      Stack name of Image Builder.
  KinesisStreamName:
    Default: stream
    Type: String
    Description: >
      Stack name of Image Builder.
  KinesisStreamShardCount:
    Default: 1
    Type: Number
    Description: >
      Stack name of Image Builder.
  KinesisStreamMode:
    Default: ON_DEMAND
    Type: String
    Description: >
      Specifies the capacity mode to which you want to set your data stream.
  KinesisStreamRetentionHours:
    Default: 24
    Type: Number
    MinValue: 24
    MaxValue: 8760
    Description: >
      The number of hours for the data records that are stored in shards to remain accessible.
  KinesisFirehoseBufferTime:
    Default: 60
    Type: Number
    MinValue: 60
    MaxValue: 900
    Description: >
      Buffer incoming data for the specified period of time, in seconds, before delivering it to the destination.
  KinesisFirehoseBufferSize:
    Default: 1
    Type: Number
    MinValue: 1
    MaxValue: 128
    Description: >
      Buffer incoming data to the specified size, in MiBs, before delivering it to the destination.
  KinesisFirehoseS3Prefix:
    Default: 'firehose'
    Type: String
    Description: >
      A prefix that Kinesis Data Firehose evaluates and adds to records before writing them to S3.
  ElbType:
    Default: 'application'
    Type: String
    AllowedValues:
      - 'application'
      - 'network'
    Description: >
      The type of load balancer.
  ElbListenerPort:
    Default: 8080
    Type: Number
    Description: >
      Stack name of Image Builder.
  ElbCertificateArn:
    Default: 'arn:aws:acm:us-east-1:123:certificate/abc-def'
    Type: String
    Description: >
      ACM Certificate ARN for NLB.
  EnableAccelerator:
    Default: 'false'
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Description: >
      Whether to enable AGA.
  DataRecordsBucket:
    Default: 's3-bucket'
    Type: String
    Description: >
      Data records bucket.
Conditions:
  UseElbCertificate:
    !Not [!Equals [!Ref ElbCertificateArn, '']]
  UseAccelerator:
    !Not [!Equals [!Ref EnableAccelerator, 'false']]
  CreateAlb:
    !Equals [!Ref ElbType, 'application']
  CreateNlb:
    !Equals [!Ref ElbType, 'network']
  ProvisionedKdsMode:
    !Equals [!Ref KinesisStreamMode, 'PROVISIONED']
Resources:
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateAlb
    Properties:
      GroupName: !Join ['-', [!Ref Prefix, 'alb-sg']]
      GroupDescription: 'Enable HTTP access on ALB listener port.'
      VpcId:
        Fn::ImportValue: !Sub '${BasicStack}-Vpc'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ElbListenerPort
          ToPort: !Ref ElbListenerPort
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: 'Name'
          Value: !Join ['-', [!Ref Prefix, 'alb-sg']]
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition: CreateAlb
    DependsOn:
      - AlbSG
    Properties: 
      Name: !Join ['-', [!Ref Prefix, 'fluentbit-alb']]
      IpAddressType: 'ipv4'
      Scheme: 'internet-facing'
      SecurityGroups:
        - !GetAtt AlbSG.GroupId
      Subnets:
        - Fn::ImportValue:
            !Sub '${BasicStack}-SubnetA'
        - Fn::ImportValue:
            !Sub '${BasicStack}-SubnetB'
      Type: !Ref ElbType
  AlbListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Condition: CreateAlb
    Properties:
      Certificates:
        - CertificateArn: !If [UseElbCertificate, !Ref ElbCertificateArn, !Ref 'AWS::NoValue']
      DefaultActions:
        - Type: "forward"
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:
                  Fn::ImportValue: !Sub '${ImagePipelineStack}-FluentBitTargetGroup'
      LoadBalancerArn: !Ref MyALB
      Port: !Ref ElbListenerPort
      Protocol: !If [UseElbCertificate, 'HTTPS', 'HTTP']
  MyNLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Condition: CreateNlb
    Properties: 
      Name: !Join ['-', [!Ref Prefix, 'fluentbit-nlb']]
      IpAddressType: 'ipv4'
      Scheme: 'internet-facing'
      Subnets:
        - Fn::ImportValue:
            !Sub '${BasicStack}-SubnetA'
        - Fn::ImportValue:
            !Sub '${BasicStack}-SubnetB'
      Type: 'network'
  NlbListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Condition: CreateNlb
    Properties:
      Certificates:
        - CertificateArn: !If [UseElbCertificate, !Ref ElbCertificateArn, !Ref 'AWS::NoValue']
      DefaultActions:
        - Type: "forward"
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn:
                  Fn::ImportValue: !Sub '${ImagePipelineStack}-FluentBitTargetGroup'
      LoadBalancerArn: !Ref MyNLB
      Port: !Ref ElbListenerPort
      Protocol: !If [UseElbCertificate, 'TLS', 'TCP']
  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['-', [!Ref Prefix, 'KinesisFirehoseRole', !Ref 'AWS::Region']]
      Description: >
        'Role used to run Fluent Bit and forward data to Kinesis Stream.'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonKinesisFullAccess'
  KinesisDataStream: 
      Type: AWS::Kinesis::Stream
      Properties: 
          Name: !Ref KinesisStreamName 
          RetentionPeriodHours: !Ref KinesisStreamRetentionHours
          ShardCount: !If [ProvisionedKdsMode, !Ref KinesisStreamShardCount, !Ref 'AWS::NoValue']
          StreamModeDetails:
            StreamMode: !Ref KinesisStreamMode
  Deliverystream: 
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - KinesisFirehoseRole
      - KinesisDataStream
    Properties:
        DeliveryStreamName: !Join ['-', [!Ref Prefix, 'delivery-stream']]
        DeliveryStreamType: KinesisStreamAsSource
        KinesisStreamSourceConfiguration: 
          KinesisStreamARN: !GetAtt KinesisDataStream.Arn
          RoleARN: !GetAtt KinesisFirehoseRole.Arn
        ExtendedS3DestinationConfiguration: 
          BucketARN: !Join [':::', ['arn:aws:s3', !Ref DataRecordsBucket]]
          BufferingHints: 
            IntervalInSeconds: !Ref KinesisFirehoseBufferTime
            SizeInMBs: !Ref KinesisFirehoseBufferSize
          CompressionFormat: UNCOMPRESSED
          Prefix: !Join ['/', [!Ref KinesisFirehoseS3Prefix, '']]
          RoleARN: !GetAtt KinesisFirehoseRole.Arn
  Accelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Name: SampleAccelerator
      Enabled: !If [UseAccelerator, true, false]
  Listener:
    Type: AWS::GlobalAccelerator::Listener
    Properties:
      AcceleratorArn:
        Ref: Accelerator
      Protocol: TCP
      PortRanges:
      - FromPort: !Ref ElbListenerPort
        ToPort: !Ref ElbListenerPort
  EndpointGroup:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      ListenerArn:
        Ref: Listener
      EndpointGroupRegion:
        Ref: 'AWS::Region'
      TrafficDialPercentage: 100
      EndpointConfigurations:
      - EndpointId: !If [CreateNlb, !Ref MyNLB, !Ref MyALB]
